version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: my-rabbit
    volumes:
      - /rabbit/data:/var/lib/rabbitmq
  mysql:
    container_name: mysql-container
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: supplier
    ports:
      - 3306:3306
    volumes:
      - /mysql/data:/var/lib/mysql